name: "Publish to Valar"
on:
  push:
    branches:    
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: valar/action@v2
      with:
        token: ${{ secrets.VALAR_TOKEN }}
